### ISSUE TITLE
Issue with generating test.py file

### ISSUE THREAD

**Issue by samkhanjar** [Fenugreek/comprehend#1]
To whom it may concern,

I would like to say thank you for this awesome library. Following the read me file to setup the library in Ubuntu operating system I faced an issue in creating the test.py file. Initially errored stating the test.py file doesn't exists. I added the file manually but and run the setup again everything seems ok but the test.py file is empty. 

Can you please help.

Thanks in advance,

Sam

**Comment by Fenugreek** [comment]
Hi Sam,

I'd removed test.py and replaced it with run.py, but had not changed the documentation to reflect that. I have now revised the documentation and took the chance to update a bunch of loose ends. 

Try again!
(Follow updated instructions in README after refreshing to current version).

Deepak

**Comment by samkhanjar** [comment]
Thank you so much Deepak for getting back to me. I will try it again and i will let you know for sure. I have one other question to ask you please. Is this library used only for images can you use this library for other purposes other than images?

**Comment by samkhanjar** [comment]
Hi Deepak, sorry to bother you with my issues. I tried running your library by typing 'python run.py --model RBM --epochs 8  --hidden 500 --batch 40 --features --output rbm_8_' as you have stated in your read me file but I get the following error:

Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from comprehend import train, features, layers, functions, mnist
  File "/usr/local/lib/python2.7/dist-packages/comprehend/layers.py", line 6, in <module>
    from comprehend import networks, features
  File "/usr/local/lib/python2.7/dist-packages/comprehend/networks.py", line 18, in <module>
    from scipy.stats import multivariate_normal
ImportError: cannot import name multivariate_normal

it can't find multivariate_normal... I'm I missing a dependency??

I'll be looking forward to hear from you very soon...

Thanks in advance,

Sam

**Comment by Fenugreek** [comment]
Hi Sam,
it looks like you either don't have scipy installed, or your scipy version is older than 0.14.0. Can you install the current version of scipy and try again? scipy can be found at http://www.scipy.org. I have now added scipy as a dependency in the README.

As for your question regarding whether this library is only for images, no, it is quite general. It takes data as input, trains a neural network, and produces other data as output. The data can be something that represents an image (defaults to MNIST, if --data option not specified to run.py), or something else. To load this data via run.py, formulate the data as a numpy array and save it to disk as a bloscpack file (extension .blp) and specify the filename through the --data option.

Deepak

**Comment by samkhanjar** [comment]
Hello Deepak, thank you so much for getting back to me. I downloaded and installed scipy just like how you mentioned but still have the same issue.

$ python run.py --model RBM --epochs 8  --hidden 500 --batch 40 --features --output rbm_8_
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    from comprehend import train, features, layers, functions, mnist
  File "/usr/local/lib/python2.7/dist-packages/comprehend/layers.py", line 6, in <module>
    from comprehend import networks, features
  File "/usr/local/lib/python2.7/dist-packages/comprehend/networks.py", line 18, in <module>
    from scipy.stats import multivariate_normal
ImportError: cannot import name multivariate_normal

I'm not sure if I'm missing something here!

Regards,

Sam

**Comment by Fenugreek** [comment]
Ok. Looks like that line 18 from File "/usr/local/lib/python2.7/dist-packages/comprehend/networks.py", is not even necessary -- can you remove that line and try again?
In a few days, I'll push some changes that will also have that line removed.

In other words, delete the line:
`from scipy.stats import multivariate_normal`

**Comment by samkhanjar** [comment]
Hi Deepak thank you so much again for your reply. I have removed the line of code you have specified in your earlier message. and now it's complaining about another thing. 

This is the error:
**hussamuk81**:~/workspace/lib/comprehend (master) $ sudo python run.py --model RBM --epochs 8  --hidden 500 --batch 40 --features --output rbm_8_                            
Traceback (most recent call last):
  File "run.py", line 92, in <module>
    logfile=logfile, printer=sys.stdout)
TypeError: __init__() got an unexpected keyword argument 'logfile'

if I run the code from this directory /usr/local/lib/python2.7/dist-packages/comprehend/ then I get a different error:
Traceback (most recent call last):
  File "run.py", line 88, in <module>
    logfile=logfile, printer=sys.stdout)
NameError: name 'sys' is not defined

I'm sorry to keep bombard you with too many issues. I really want to see how your library would work with my data.

I'll be looking forward for your reply...

Thanks in advance,

Sam

**Comment by Fenugreek** [comment]
Hi Sam,
I'd made a change to the `tamarind` project I had forgotten to push. Now pushed. Can you refresh your `tamarind` library? (Pull the recent changes.) Thanks for your patience.
Deepak

**Comment by samkhanjar** [comment]
Hi Deepak thank you again for your fast response. I made a good progress. I have updated tamarind library as you have requested and I got this far:

**hussamuk81:**~/workspace/lib/comprehend (master) $ sudo python run.py --model RBM --epochs 8  --hidden 500 --batch 40 --features --output rbm_8_
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[INFO  run.py 04:27:38] Train samples 50600, validation samples 4400
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "run.py", line 187, in <module>
    train.train(sess, coder, dataset, bptt=args.bptt, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/comprehend/train.py", line 162, in train
    cost = coder.cost(*train_args, function=costing, store=bptt)
TypeError: cost() argument after * must be a sequence, not NoneType

Now it's erroring in train.py...

Regards,

Sam

**Comment by Fenugreek** [comment]
Your `networks.py` file is slightly out of date -- I pushed in a change two days ago that no longer has that problem. Can you get the new `networks.py` file? To make it easy, I've now also removed the `from scipy.stats...` line from that file, so you don't have to do that manually again. 

Also, I made a small unrelated bug fix in `train.py` I discovered when looking into this. So get that new file too!

**Comment by samkhanjar** [comment]
Hi Deepak thank you for updating the library. I have updated your entire library on my local and I'm still getting this error:

**hussamuk81:**~/workspace/lib/comprehend (master) $ sudo python run.py --model RBM --epochs 8  --hidden 500 --batch 40 --features --output rbm_8_
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[INFO  run.py 05:16:37] Train samples 50600, validation samples 4400
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "run.py", line 187, in <module>
    train.train(sess, coder, dataset, bptt=args.bptt, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/comprehend/train.py", line 162, in train
    cost = coder.cost(*train_args, function=costing, store=bptt)
TypeError: cost() argument after * must be a sequence, not NoneType

Please let me know if you want me to try it again I'll be grateful to do that.

I'll be looking forward for your feedback...

Thanks in advance,

Sam

**Comment by Fenugreek** [comment]
Hi Sam,
I am not seeing that error on my end. To debug, can you first check again that the copy of `comprehend` you are executing matches what's on github?

In particular, I see that you have code in two locations:
`~/workspace/lib/comprehend (master) `
and
`/usr/local/lib/python2.7/dist-packages/comprehend/`

Maybe one of these locations (probably the second one) has an old out of date `networks.py` or `train.py` that's being executed?

I am going to be away for several hours; if the above doesn't provide a resolution, but you know python and want to poke around:

`train_args` in your line 162 of `train.py` seems to be `None` instead of a list. This means that line 161 of `train.py` evaluated to `None` instead of a list. 

Which means that the `init_train_args()` method of the `networks.RBM` class in `networks.py` returned `None` instead of a list. But you can see from the current `networks.py` code that this should not be possible. That's why this is a puzzle.

**Comment by samkhanjar** [comment]
Hi Deepak thank you again for getting back to me on this so quikly. Im currently on the train back home. I will try the following.

1. Ill delete your library from both locations on my local.
2. Pull the latest code
3. Install the library under /usr/local/lib/python2.7/dist-packages/
4. Run the library

I will let you know once i do all the steps above.

Thank you again for all the help and support.

Regards,

Sam

**Comment by samkhanjar** [comment]
Thank you so much Deepak. I got it to work now thank you :)... I will try it with my data at some stage. Thank you for this brilliant library.

Regards,

Sam

**Comment by samkhanjar** [comment]
Hi Deepak, the code seems to work with Model RBM but if I change the model to RNN I get the following error:

**hussamuk81:**/usr/local/lib/python2.7/dist-packages/comprehend (master) $ sudo python run.py --model RNN --epochs 10  --hidden 500 --batch 40 --features --output rbm_8_                                                                                                                                            
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[INFO  run.py 10:02:30] Train samples 50600, validation samples 4400
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "run.py", line 187, in <module>
    train.train(sess, coder, dataset, bptt=args.bptt, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/comprehend/train.py", line 162, in train
    cost = coder.cost(*train_args, function=costing, store=bptt)
  File "/usr/local/lib/python2.7/dist-packages/comprehend/networks.py", line 247, in cost
    loss = function(inputs, self.recode(inputs, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/comprehend/networks.py", line 1264, in recode
    states=[], as_list=True, store=store)
  File "/usr/local/lib/python2.7/dist-packages/comprehend/networks.py", line 1214, in seq_update
    for i, row in enumerate(tf.unpack(tf.transpose(inputs, perm=[2, 0, 1]))):
AttributeError: 'module' object has no attribute 'unpack' 

Regards,

Sam

**Comment by Fenugreek** [comment]
Hi Sam,
great!

The new error for the RNN code is because you are using a newer version of Tensorflow than mine -- in your version, `tf.unpack` has been renamed to `tf.unstack`.  I've now renamed it and fixed a couple other small errors (in `networks.py` and `run.py`). Try again after refreshing. Also, you might not have enough memory for an RNN with 500 hidden units -- try 100 hidden units if you get memory errors.

I am not 100% sure it will work for you, because I am still using the older version of Tensorflow and can't test the `tf.unstack` change. I'll try to upgrade my version and test everything by end of next week.

I am closing this request. Please open a new one in case of further issues.

Thanks,
Deepak
